=== SISA0729/LM/ejercicios/alumno/alumno.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alumno">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"/>
                <xs:element name="direccion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="calle" type="xs:string" />
                            <xs:element name="numero">
                                <xs:complexType>
                                    
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="ciudad" type="xs:string"/>
                            <xs:element name="provincia" type="xs:string"/>
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="telefono" minOccurs="0" maxOccurs="5"/>
            </xs:sequence>
            <xs:attribute name="dni">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="5"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SISA0729/LM/ejercicios/alumno/alumno.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumno
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="alumno.xsd">
    <nombre>Juan Garcia</nombre>
    <direccion>
        <calle>Avenida de la Fuente</calle>
        <numero>6</numero>
        <ciudad>Zafra</ciudad>
        <provincia>Badajoz</provincia>
    </direccion>
    <telefono>666666666</telefono>
    <telefeno>999999999</telefeno>
</alumno>
